import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3D5CFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(20),
    paddingTop: verticalScale(50),
    paddingBottom: verticalScale(20),
  },
  backButton: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    fontSize: moderateScale(24),
    color: '#FFFFFF',
  },
  headerRight: {
    flexDirection: 'row',
    gap: scale(10),
  },
  favoriteButton: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewButton: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  favoriteIcon: {
    fontSize: moderateScale(20),
  },
  imageContainer: {
    alignItems: 'center',
    paddingVertical: verticalScale(30),
  },
  imagePlaceholder: {
    width: scale(250),
    height: scale(250),
    borderRadius: scale(125),
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  productEmoji: {
    fontSize: moderateScale(120),
  },
  contentContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: moderateScale(30),
    borderTopRightRadius: moderateScale(30),
    paddingHorizontal: scale(20),
    paddingTop: verticalScale(25),
    paddingBottom: verticalScale(30),
  },
  ratingContainer: {
    alignItems: 'flex-end',
    marginBottom: verticalScale(20),
  },
  ratingBadge: {
    backgroundColor: '#3D5CFF',
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(6),
    borderRadius: moderateScale(20),
  },
  ratingText: {
    color: '#FFFFFF',
    fontSize: moderateScale(14),
    fontWeight: '600',
  },
  productTitle: {
    fontSize: moderateScale(28),
    fontWeight: 'bold',
    color: '#333',
    marginBottom: verticalScale(10),
  },
  productDescription: {
    fontSize: moderateScale(14),
    color: '#666',
    lineHeight: moderateScale(20),
    marginBottom: verticalScale(25),
  },
  section: {
    marginBottom: verticalScale(25),
  },
  sectionTitle: {
    fontSize: moderateScale(18),
    fontWeight: '600',
    color: '#333',
    marginBottom: verticalScale(15),
  },
  addOnsContainer: {
    flexDirection: 'row',
    gap: scale(15),
  },
  addOnCard: {
    width: scale(70),
    height: scale(70),
    borderRadius: moderateScale(15),
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  addOnCardSelected: {
    backgroundColor: '#3D5CFF',
  },
  addOnEmoji: {
    fontSize: moderateScale(35),
  },
  checkmark: {
    position: 'absolute',
    top: verticalScale(5),
    right: scale(5),
    width: scale(20),
    height: scale(20),
    borderRadius: scale(10),
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkmarkText: {
    color: '#FFFFFF',
    fontSize: moderateScale(12),
    fontWeight: 'bold',
  },
  bottomSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(20),
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: moderateScale(25),
    padding: moderateScale(5),
  },
  quantityButton: {
    width: scale(35),
    height: scale(35),
    borderRadius: scale(17.5),
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonText: {
    fontSize: moderateScale(20),
    color: '#333',
    fontWeight: '600',
  },
  quantityText: {
    fontSize: moderateScale(18),
    fontWeight: '600',
    color: '#333',
    marginHorizontal: scale(20),
  },
  priceContainer: {
    alignItems: 'flex-end',
  },
  priceLabel: {
    fontSize: moderateScale(14),
    color: '#666',
    marginBottom: verticalScale(3),
  },
  priceValue: {
    fontSize: moderateScale(28),
    fontWeight: 'bold',
    color: '#FFB800',
  },
  addToCartButton: {
    backgroundColor: '#3D5CFF',
    paddingVertical: verticalScale(16),
    borderRadius: moderateScale(25),
    alignItems: 'center',
    shadowColor: '#3D5CFF',
    shadowOffset: { width: 0, height: verticalScale(4) },
    shadowOpacity: 0.3,
    shadowRadius: moderateScale(8),
    elevation: 5,
  },
  addToCartText: {
    color: '#FFFFFF',
    fontSize: moderateScale(18),
    fontWeight: 'bold',
  },
  productImage: {
    width: scale(250),
    height: scale(250),
    borderRadius: scale(125),
  },
  restaurantName: {
    fontSize: moderateScale(14),
    color: '#999',
    marginBottom: verticalScale(8),
  },
  noImageContainer: {
    width: scale(250),
    height: scale(250),
    borderRadius: scale(125),
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noImageText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: moderateScale(14),
    marginTop: verticalScale(10),
    fontWeight: '600',
  },
});