import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(20),
    paddingTop: verticalScale(50),
    paddingBottom: verticalScale(20),
    backgroundColor: '#FFFFFF',
  },
  headerTitle: {
    fontSize: moderateScale(28),
    fontWeight: 'bold',
    color: '#333',
  },
  cartIcon: {
    position: 'relative',
    width: scale(50),
    height: scale(50),
    borderRadius: scale(25),
    backgroundColor: '#3D5CFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartIconText: {
    fontSize: moderateScale(24),
  },
  cartBadge: {
    position: 'absolute',
    top: verticalScale(-5),
    right: scale(-5),
    backgroundColor: '#FF6B6B',
    borderRadius: moderateScale(10),
    width: scale(20),
    height: verticalScale(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartBadgeText: {
    color: '#FFFFFF',
    fontSize: moderateScale(12),
    fontWeight: 'bold',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFEFEF',
    marginHorizontal: scale(20),
    marginTop: verticalScale(20),
    paddingHorizontal: scale(15),
    paddingVertical: verticalScale(12),
    borderRadius: moderateScale(12),
  },
  searchIcon: {
    fontSize: moderateScale(18),
    marginRight: scale(10),
  },
  searchPlaceholder: {
    fontSize: moderateScale(16),
    color: '#999',
  },
  categoriesContainer: {
    marginTop: verticalScale(20),
    paddingHorizontal: scale(20),
  },
  categoryCard: {
    width: scale(60),
    height: scale(60),
    borderRadius: moderateScale(15),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(15),
  },
  categoryEmoji: {
    fontSize: moderateScale(30),
  },
  categoryImage: {
    width: scale(60),
    height: scale(60),
    borderRadius: moderateScale(15),
  },
  section: {
    marginTop: verticalScale(25),
    paddingHorizontal: scale(20),
  },
  sectionTitle: {
    fontSize: moderateScale(20),
    fontWeight: 'bold',
    color: '#333',
    marginBottom: verticalScale(15),
  },
  promotionCard: {
    backgroundColor: '#3D5CFF',
    borderRadius: moderateScale(15),
    padding: moderateScale(20),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  promotionContent: {
    flex: 1,
  },
  promotionBadge: {
    color: '#FFFFFF',
    fontSize: moderateScale(12),
    marginBottom: verticalScale(5),
    opacity: 0.9,
  },
  promotionTitle: {
    color: '#FFFFFF',
    fontSize: moderateScale(18),
    fontWeight: 'bold',
    marginBottom: verticalScale(3),
  },
  promotionSubtitle: {
    color: '#FFFFFF',
    fontSize: moderateScale(12),
    opacity: 0.9,
  },
  promotionImage: {
    width: scale(80),
    height: scale(80),
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: scale(40),
    alignItems: 'center',
    justifyContent: 'center',
  },
  promotionEmoji: {
    fontSize: moderateScale(40),
  },
  itemCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(12),
    padding: moderateScale(12),
    marginBottom: verticalScale(12),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: verticalScale(2) },
    shadowOpacity: 0.1,
    shadowRadius: moderateScale(4),
    elevation: 2,
  },
  itemImagePlaceholder: {
    width: scale(70),
    height: scale(70),
    backgroundColor: '#F5F5F5',
    borderRadius: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemEmoji: {
    fontSize: moderateScale(35),
  },
  itemInfo: {
    flex: 1,
    marginLeft: scale(15),
  },
  itemName: {
    fontSize: moderateScale(16),
    fontWeight: '600',
    color: '#333',
    marginBottom: verticalScale(5),
  },
  itemPrice: {
    fontSize: moderateScale(14),
    color: '#FFB800',
    fontWeight: 'bold',
  },
  ratingBadge: {
    backgroundColor: '#3D5CFF',
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(8),
  },
  ratingText: {
    color: '#FFFFFF',
    fontSize: moderateScale(12),
    fontWeight: '600',
  },
});