import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3D5CFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(20),
    paddingTop: verticalScale(50),
    paddingBottom: verticalScale(20),
  },
  headerTitle: {
    fontSize: moderateScale(24),
    fontWeight: 'bold',
    color: '#FFF',
  },
  editButton: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileCard: {
    backgroundColor: '#FFF',
    marginHorizontal: scale(20),
    marginTop: verticalScale(10),
    marginBottom: verticalScale(20),
    borderRadius: moderateScale(20),
    padding: scale(25),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: verticalScale(4) },
    shadowOpacity: 0.1,
    shadowRadius: moderateScale(8),
    elevation: 5,
  },
  avatarContainer: {
    position: 'relative',
    marginBottom: verticalScale(15),
  },
  avatar: {
    width: scale(100),
    height: scale(100),
    borderRadius: scale(50),
    backgroundColor: '#FFE5E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: scale(32),
    height: scale(32),
    borderRadius: scale(16),
    backgroundColor: '#FF6B6B',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FFF',
  },
  userName: {
    fontSize: moderateScale(24),
    fontWeight: 'bold',
    color: '#333',
    marginBottom: verticalScale(5),
  },
  userEmail: {
    fontSize: moderateScale(14),
    color: '#666',
    marginBottom: verticalScale(20),
  },
  statsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingTop: verticalScale(20),
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statValue: {
    fontSize: moderateScale(22),
    fontWeight: 'bold',
    color: '#FF6B6B',
    marginBottom: verticalScale(5),
  },
  statLabel: {
    fontSize: moderateScale(12),
    color: '#666',
  },
  statDivider: {
    width: 1,
    height: verticalScale(40),
    backgroundColor: '#F0F0F0',
  },
  menuContainer: {
    backgroundColor: '#FFF',
    marginHorizontal: scale(20),
    borderRadius: moderateScale(20),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: verticalScale(2) },
    shadowOpacity: 0.1,
    shadowRadius: moderateScale(4),
    elevation: 3,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(16),
    paddingHorizontal: scale(20),
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  menuItemIconContainer: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: '#FFE5E5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(15),
  },
  menuItemText: {
    fontSize: moderateScale(16),
    color: '#333',
    fontWeight: '500',
  },
  menuItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  badge: {
    backgroundColor: '#FF6B6B',
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(2),
    borderRadius: moderateScale(10),
    marginRight: scale(8),
  },
  badgeText: {
    color: '#FFF',
    fontSize: moderateScale(12),
    fontWeight: '600',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF',
    marginHorizontal: scale(20),
    marginTop: verticalScale(20),
    marginBottom: verticalScale(10),
    paddingVertical: verticalScale(16),
    borderRadius: moderateScale(20),
    borderWidth: 1,
    borderColor: '#FF6B6B',
  },
  logoutButtonText: {
    fontSize: moderateScale(16),
    color: '#FF6B6B',
    fontWeight: '600',
    marginLeft: scale(10),
  },
  versionText: {
    textAlign: 'center',
    color: 'rgba(255,255,255,0.7)',
    fontSize: moderateScale(12),
    marginTop: verticalScale(10),
    marginBottom: verticalScale(30),
  },
});