import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    paddingHorizontal: scale(20),
    paddingTop: verticalScale(50),
    paddingBottom: verticalScale(20),
    backgroundColor: '#FFFFFF',
  },
  headerTitle: {
    fontSize: moderateScale(24),
    fontWeight: 'bold',
    color: '#333',
  },
  cartItem: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    marginHorizontal: scale(20),
    marginTop: verticalScale(15),
    padding: moderateScale(15),
    borderRadius: moderateScale(15),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: verticalScale(2) },
    shadowOpacity: 0.1,
    shadowRadius: moderateScale(4),
    elevation: 2,
  },
  itemImagePlaceholder: {
    width: scale(60),
    height: scale(60),
    backgroundColor: '#F5F5F5',
    borderRadius: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemEmoji: {
    fontSize: moderateScale(30),
  },
  itemDetails: {
    flex: 1,
    marginLeft: scale(15),
  },
  itemName: {
    fontSize: moderateScale(16),
    fontWeight: '600',
    color: '#333',
    marginBottom: verticalScale(5),
  },
  itemPrice: {
    fontSize: moderateScale(14),
    color: '#FFB800',
    fontWeight: 'bold',
  },
  itemQuantity: {
    fontSize: moderateScale(12),
    color: '#999',
    marginTop: verticalScale(3),
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: moderateScale(20),
    padding: moderateScale(3),
  },
  quantityButton: {
    width: scale(28),
    height: scale(28),
    borderRadius: scale(14),
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonText: {
    fontSize: moderateScale(16),
    color: '#333',
    fontWeight: '600',
  },
  quantityText: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: '#333',
    marginHorizontal: scale(12),
  },
  section: {
    marginHorizontal: scale(20),
    marginTop: verticalScale(25),
  },
  sectionTitle: {
    fontSize: moderateScale(16),
    fontWeight: '600',
    color: '#333',
    marginBottom: verticalScale(10),
  },
  instructionsBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(12),
    padding: moderateScale(15),
    minHeight: verticalScale(80),
  },
  instructionsPlaceholder: {
    color: '#333',
    fontSize: moderateScale(14),
  },
  summarySection: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: scale(20),
    marginTop: verticalScale(25),
    marginBottom: verticalScale(20),
    padding: moderateScale(20),
    borderRadius: moderateScale(15),
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: verticalScale(12),
  },
  summaryLabel: {
    fontSize: moderateScale(14),
    color: '#666',
  },
  summaryValue: {
    fontSize: moderateScale(14),
    color: '#333',
    fontWeight: '500',
  },
  divider: {
    height: 1,
    backgroundColor: '#E0E0E0',
    marginVertical: verticalScale(10),
  },
  totalLabel: {
    fontSize: moderateScale(18),
    fontWeight: 'bold',
    color: '#333',
  },
  totalValue: {
    fontSize: moderateScale(24),
    fontWeight: 'bold',
    color: '#FFB800',
  },
  checkoutContainer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: scale(20),
    paddingVertical: verticalScale(15),
    paddingBottom: verticalScale(80),
    // borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  checkoutButton: {
    backgroundColor: '#3D5CFF',
    paddingVertical: verticalScale(16),
    borderRadius: moderateScale(25),
    alignItems: 'center',
    marginBottom: verticalScale(10),
  },
  checkoutText: {
    color: '#FFFFFF',
    fontSize: moderateScale(18),
    fontWeight: 'bold',
  },
  backToMenuButton: {
    paddingVertical: verticalScale(12),
    alignItems: 'center',
  },
  backToMenuText: {
    color: '#3D5CFF',
    fontSize: moderateScale(16),
    fontWeight: '600',
  },
  checkoutButtonDisabled: {
    backgroundColor: '#CCCCCC',
    opacity: 0.6,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(20),
    padding: moderateScale(30),
    width: '85%',
    maxWidth: scale(400),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: verticalScale(10) },
    shadowOpacity: 0.25,
    shadowRadius: moderateScale(10),
    elevation: 10,
  },
  modalIconContainer: {
    marginBottom: verticalScale(20),
  },
  modalTitle: {
    fontSize: moderateScale(24),
    fontWeight: 'bold',
    color: '#333',
    marginBottom: verticalScale(10),
    textAlign: 'center',
  },
  modalMessage: {
    fontSize: moderateScale(16),
    color: '#666',
    textAlign: 'center',
    marginBottom: verticalScale(20),
    lineHeight: moderateScale(22),
  },
  modalOrderSummary: {
    width: '100%',
    backgroundColor: '#F5F5F5',
    borderRadius: moderateScale(12),
    padding: moderateScale(15),
    marginBottom: verticalScale(15),
  },
  modalSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: verticalScale(8),
  },
  modalSummaryLabel: {
    fontSize: moderateScale(14),
    color: '#666',
  },
  modalSummaryValue: {
    fontSize: moderateScale(14),
    color: '#333',
    fontWeight: '500',
  },
  modalSummaryValueBold: {
    fontSize: moderateScale(16),
    color: '#FFB800',
    fontWeight: 'bold',
  },
  modalDeliveryText: {
    fontSize: moderateScale(14),
    color: '#4CAF50',
    marginBottom: verticalScale(25),
    textAlign: 'center',
    fontWeight: '500',
  },
  modalButton: {
    backgroundColor: '#3D5CFF',
    paddingVertical: verticalScale(14),
    paddingHorizontal: scale(40),
    borderRadius: moderateScale(25),
    width: '100%',
    alignItems: 'center',
    marginBottom: verticalScale(10),
  },
  modalButtonText: {
    color: '#FFFFFF',
    fontSize: moderateScale(16),
    fontWeight: 'bold',
  },
  modalButtonSecondary: {
    paddingVertical: verticalScale(12),
    paddingHorizontal: scale(40),
    width: '100%',
    alignItems: 'center',
  },
  modalButtonSecondaryText: {
    color: '#3D5CFF',
    fontSize: moderateScale(16),
    fontWeight: '600',
  },
  emptyCart: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: verticalScale(80),
  },
  emptyCartText: {
    fontSize: moderateScale(18),
    fontWeight: '600',
    color: '#666',
    marginTop: verticalScale(20),
  },
  emptyCartSubtext: {
    fontSize: moderateScale(14),
    color: '#999',
    marginTop: verticalScale(8),
  },
  itemImage: {
    width: scale(60),
    height: scale(60),
    borderRadius: moderateScale(12),
  },
  addOnsText: {
    fontSize: moderateScale(11),
    color: '#999',
    marginTop: verticalScale(3),
    fontStyle: 'italic',
  },
});